// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/parser.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MenuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"` // "kfc" или "mac"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuRequest) Reset() {
	*x = MenuRequest{}
	mi := &file_proto_parser_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuRequest) ProtoMessage() {}

func (x *MenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_parser_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuRequest.ProtoReflect.Descriptor instead.
func (*MenuRequest) Descriptor() ([]byte, []int) {
	return file_proto_parser_proto_rawDescGZIP(), []int{0}
}

func (x *MenuRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type MenuResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawXml        string                 `protobuf:"bytes,1,opt,name=raw_xml,json=rawXml,proto3" json:"raw_xml,omitempty"` // Огромная сырая XML-строка, снятая с экрана телефона
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuResponse) Reset() {
	*x = MenuResponse{}
	mi := &file_proto_parser_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuResponse) ProtoMessage() {}

func (x *MenuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_parser_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuResponse.ProtoReflect.Descriptor instead.
func (*MenuResponse) Descriptor() ([]byte, []int) {
	return file_proto_parser_proto_rawDescGZIP(), []int{1}
}

func (x *MenuResponse) GetRawXml() string {
	if x != nil {
		return x.RawXml
	}
	return ""
}

var File_proto_parser_proto protoreflect.FileDescriptor

const file_proto_parser_proto_rawDesc = "" +
	"\n" +
	"\x12proto/parser.proto\x12\n" +
	"aggregator\")\n" +
	"\vMenuRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\"'\n" +
	"\fMenuResponse\x12\x17\n" +
	"\araw_xml\x18\x01 \x01(\tR\x06rawXml2U\n" +
	"\x0ePhoneUiService\x12C\n" +
	"\x0eGetRawMenuDump\x12\x17.aggregator.MenuRequest\x1a\x18.aggregator.MenuResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_proto_parser_proto_rawDescOnce sync.Once
	file_proto_parser_proto_rawDescData []byte
)

func file_proto_parser_proto_rawDescGZIP() []byte {
	file_proto_parser_proto_rawDescOnce.Do(func() {
		file_proto_parser_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_parser_proto_rawDesc), len(file_proto_parser_proto_rawDesc)))
	})
	return file_proto_parser_proto_rawDescData
}

var file_proto_parser_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_parser_proto_goTypes = []any{
	(*MenuRequest)(nil),  // 0: aggregator.MenuRequest
	(*MenuResponse)(nil), // 1: aggregator.MenuResponse
}
var file_proto_parser_proto_depIdxs = []int32{
	0, // 0: aggregator.PhoneUiService.GetRawMenuDump:input_type -> aggregator.MenuRequest
	1, // 1: aggregator.PhoneUiService.GetRawMenuDump:output_type -> aggregator.MenuResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_parser_proto_init() }
func file_proto_parser_proto_init() {
	if File_proto_parser_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_parser_proto_rawDesc), len(file_proto_parser_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_parser_proto_goTypes,
		DependencyIndexes: file_proto_parser_proto_depIdxs,
		MessageInfos:      file_proto_parser_proto_msgTypes,
	}.Build()
	File_proto_parser_proto = out.File
	file_proto_parser_proto_goTypes = nil
	file_proto_parser_proto_depIdxs = nil
}
