// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.4
// source: proto/parser.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PhoneUiService_GetRawMenuDump_FullMethodName = "/aggregator.PhoneUiService/GetRawMenuDump"
)

// PhoneUiServiceClient is the client API for PhoneUiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PhoneUiServiceClient interface {
	// Метод, который Scanner будет вызывать по сети
	GetRawMenuDump(ctx context.Context, in *MenuRequest, opts ...grpc.CallOption) (*MenuResponse, error)
}

type phoneUiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPhoneUiServiceClient(cc grpc.ClientConnInterface) PhoneUiServiceClient {
	return &phoneUiServiceClient{cc}
}

func (c *phoneUiServiceClient) GetRawMenuDump(ctx context.Context, in *MenuRequest, opts ...grpc.CallOption) (*MenuResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MenuResponse)
	err := c.cc.Invoke(ctx, PhoneUiService_GetRawMenuDump_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PhoneUiServiceServer is the server API for PhoneUiService service.
// All implementations must embed UnimplementedPhoneUiServiceServer
// for forward compatibility.
type PhoneUiServiceServer interface {
	// Метод, который Scanner будет вызывать по сети
	GetRawMenuDump(context.Context, *MenuRequest) (*MenuResponse, error)
	mustEmbedUnimplementedPhoneUiServiceServer()
}

// UnimplementedPhoneUiServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPhoneUiServiceServer struct{}

func (UnimplementedPhoneUiServiceServer) GetRawMenuDump(context.Context, *MenuRequest) (*MenuResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRawMenuDump not implemented")
}
func (UnimplementedPhoneUiServiceServer) mustEmbedUnimplementedPhoneUiServiceServer() {}
func (UnimplementedPhoneUiServiceServer) testEmbeddedByValue()                        {}

// UnsafePhoneUiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PhoneUiServiceServer will
// result in compilation errors.
type UnsafePhoneUiServiceServer interface {
	mustEmbedUnimplementedPhoneUiServiceServer()
}

func RegisterPhoneUiServiceServer(s grpc.ServiceRegistrar, srv PhoneUiServiceServer) {
	// If the following call panics, it indicates UnimplementedPhoneUiServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PhoneUiService_ServiceDesc, srv)
}

func _PhoneUiService_GetRawMenuDump_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MenuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhoneUiServiceServer).GetRawMenuDump(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PhoneUiService_GetRawMenuDump_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhoneUiServiceServer).GetRawMenuDump(ctx, req.(*MenuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PhoneUiService_ServiceDesc is the grpc.ServiceDesc for PhoneUiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PhoneUiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aggregator.PhoneUiService",
	HandlerType: (*PhoneUiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRawMenuDump",
			Handler:    _PhoneUiService_GetRawMenuDump_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/parser.proto",
}
